import React, { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";

//!COMPONENTS
import ScreenAbout from "src/screens/about";

const PageAbout: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>À propos de moi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ScreenAbout />
      </main>
    </Fragment>
  );
};

export default PageAbout;
