import React, { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";

//!COMPONENTS

const PageBlog: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>About</main>
    </Fragment>
  );
};

export default PageBlog;
