import React, { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";

//!COMPONENTS
import ScreenHome from "src/screens/home";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ScreenHome />
      </main>
    </Fragment>
  );
};

export default Home;
